name: mi_calculadora
description: Una calculadora de mesa de senos.

# Previene publicaciones accidentales en pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# ===================================================================
# SECCIÓN CORREGIDA
# ===================================================================
# Las dependencias deben estar al mismo nivel de indentación.
dependencies:
  flutter:
    sdk: flutter

  # Cada una de estas es una dependencia separada.
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# Configuración específica de Flutter.
flutter:
  uses-material-design: true

  # Si tienes assets (imágenes, fuentes), se declaran aquí.
  # assets:
  #   - assets/images/
